---
  - name: Create Storidge Cluster
    hosts: masters
    become: true
    gather_facts: False
    tasks:
      - name: get join token from active cluster
        shell: >
          cioctl join-token | awk '/cioctl node add/ {print $5}'
        register: jointoken

      - name: create cluster
        shell: >
          cioctl create --ip {{ private_ip }} | awk '/cioctl join/ {print $4}'
        register: clustertoken
        when: "jointoken.stdout == ''"

  - name: Join Storidge Nodes
    hosts: workers
    become: true
    gather_facts: False
    vars:
      clustertoken: "{{ hostvars[groups['masters'][0]]['clustertoken'] }}"
      jointoken: "{{ hostvars[groups['masters'][0]]['jointoken'] }}"
      master: "{{ hostvars[groups['masters'][0]]['private_ip'] }}"
    tasks:
      - name: check if already a cluster member
        stat:
          path: /etc/storidge/nodeid
        register: nodeid

      - name: join nodes to cio cluster
        command: "cioctl join {{ master }} {{ clustertoken.stdout|default(jointoken.stdout) }} --ip {{ private_ip }}"
        register: result
        until: result.stdout.find("Adding this node") != -1
        retries: 5
        delay: 1

  - name: Initialize Storidge Cluster
    hosts: masters
    become: true
    gather_facts: False
    vars:
      clustertoken: "{{ hostvars[groups['masters'][0]]['clustertoken'] }}"
    tasks:
      - name: cioctl init
        command: "cioctl init {{ clustertoken.stdout.split('-')[1] }}"
        register: clusterinit
        when: "clustertoken is not skipped"

      - name: show cluster init output
        debug: var=clusterinit.stdout

      - name: show cluster init error
        debug: var=clusterinit.stderr
