---
  - name: Init Swarm Master
    hosts: masters
    become: true
    gather_facts: False
    tasks:
      - name: determine swarm status
        shell: >
          docker info | egrep '^Swarm: ' | cut -d ' ' -f2
        register: swarm_status

      - name: Set authorized key for deployment
        authorized_key:
          user: root
          state: present
          key: "{{ deploy_pub_key }}"

      - name: Swarm Init
        command: docker swarm init --advertise-addr {{ private_ip }}
        when: "'active' not in swarm_status.stdout_lines"

      - name: Get Worker Token
        command: docker swarm join-token worker -q
        register: worker_token

      - name: Get Master Token
        command: docker swarm join-token manager -q
        register: master_token

  - name: Join Swarm Cluster
    hosts: workers
    become: true
    gather_facts: False
    vars:
      token: "{{ hostvars[groups['masters'][0]]['worker_token']['stdout'] }}"
      master: "{{ hostvars[groups['masters'][0]]['private_ip'] }}"
    tasks:
      - name: determine swarm status
        shell: >
          docker info | egrep '^Swarm: ' | cut -d ' ' -f2
        register: swarm_status

      - name: Join Swarm Cluster as a Worker
        command: docker swarm join --token {{ token }} {{ master }}:2377
        register: worker
        when: "'active' not in swarm_status.stdout_lines"

  - name: Init Storidge Master
    hosts: masters
    become: true
    gather_facts: False
    tasks:
      - name: try to get join token from active cluster
        shell: >
          cioctl join-token | awk '/cioctl join/ {print $5}'
        register: jointoken

      - name: create a new cluster
        shell: >
          cioctl create --ip {{ private_ip }} | awk '/cioctl join/ {print $5}'
        register: clustertoken
        when: "jointoken.stdout == ''"

  - name: Join Storidge Nodes
    hosts: workers
    become: true
    gather_facts: False
    vars:
      clustertoken: "{{ hostvars[groups['masters'][0]]['clustertoken'] }}"
      jointoken: "{{ hostvars[groups['masters'][0]]['jointoken'] }}"
      master: "{{ hostvars[groups['masters'][0]]['private_ip'] }}"
    tasks:
      - name: check if already a cluster member
        stat:
          path: /etc/convergeio/nodeid
        register: nodeid

      - name: cioctl join on nodes
        command: "cioctl join {{ master }} root {{ clustertoken.stdout|default(jointoken.stdout) }} --ip {{ private_ip }}"
        when: "nodeid.stat.exists == False"

  - name: Add Nodes To Master
    hosts: masters
    become: true
    gather_facts: False
    tasks:
      - name: cioctl init
        command: "cioctl init {{ clustertoken.stdout }}"
        register: clusterinit
        when: "clustertoken is not skipped"

      - name: show cluster init output
        debug: var=clusterinit.stdout

      - name: show cluster init error
        debug: var=clusterinit.stderr
